# Generated by Django 5.0.3 on 2024-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_basketballplayer_basketballteam_footballplayer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballplayer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='footballplayer',
            name='age',
        ),
        migrations.AlterField(
            model_name='basketballteam',
            name='conference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='conference',
            field=models.CharField(max_length=255),
        ),
    ]
