# Generated by Django 5.0.3 on 2024-03-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_basketballplayer_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basketballPlayer',
        ),
        migrations.DeleteModel(
            name='basketballTeam',
        ),
        migrations.DeleteModel(
            name='footballTeam',
        ),
    ]
