# Generated by Django 5.0.3 on 2024-03-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_basketballplayer_delete_basketballteam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='basketballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
