# Generated by Django 5.0.3 on 2024-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_basketballplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='footballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
                ('quarterback', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
